project:
  type: website
  output-dir: docs
  resources:
    - practicals/data/*

website:
  title: "Causal prediction for medical decision making: Methods and Practice"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
