#+TITLE: Practicals Day 1 Morning Session
#+AUTHOR: PhD course: Causal prediction for medical decision making
#+DATE: 
#+setupfile:~/emacs-genome/snps/org-templates/setup-demografi.org
#+superman-org-export-target: practical
#+OPTIONS: :rmd_yaml:nil

* Exercise 1

Consider the CVD risk prediction tool for type 1 diabetes (Steno
Diabetes Center Copenhagen): https://steno.shinyapps.io/T1RiskEngine/
\vspace{1em}

\noindent Answer the following questions:

1. Who is eligible to use this calculator?
2. At what occasion can people use this calculator (i.e., what is time zero)?
3. In what direction does the 5-year risk change when you change any of the predictor variables keeping the other predictor variables at a fixed value?
4. What other risk predictor variables does the Framingham CVD risk calculator use? https://static.heart.org/riskcalc/app/index.html

\noindent Think about and discuss the following with your nearest neighbors:

5. [@5] What possible applications does this medical risk prediction model have?
6. Which of the risk factors may change over time?
7. How old (relative to time zero) are the measurements of these risk factors allowed to be?
8. Which of the risk factors are modifiable? 
9. Correspondingly what would be possible interventions?
10. Decision making (for versus against an intervention) could be based on comparing the predicted 5-year risk to a fixed threshold, e.g., 10%. How would one incorporate lower and upper limits for the predicted risks to guide a person's decision?

** COMMENT Additional discussion

\noindent Answer the following questions regarding the statistical
methods behind the risk engine by reading the section Statistical
Analysis in the article and the model formula in the supplementary
material (below Supplemental Table 3).

https://www.ahajournals.org/doi/full/10.1161/CIRCULATIONAHA.115.018844

1. [@11] How large was the sample size of the derivation cohort? How long was the follow-up? What is the interpretation of the probability 18.4%?
2. What variable selection methods were applied in the two steps of the analysis?
3. How many parameters were used to model the baseline hazard function in the final model formula?
4. Which results of step 1 of the analysis had an influence on the linear predictor?
5. How does the ignorance of competing risk of death without CVD affect the interpretation of the results?
6. Is the interpretation of the c-statistic clear? 

** Solutions :solution:ignore:

\noindent Answers to the questions:

1. [@1] Who is eligible to use this calculator?

People with a type I diabetes diagnosis who are between 18 and 100
years old without a previous CVD event.

2. [@2] At what occasion can people use this calculator (i.e., what is time zero)?

This is not explicitly stated but it seems reasonable to assume that
time zero is when the date of a measurement of the variables HbA1c,
Systolic blood pressure, Albuminuria, eGFR, LDL.

3. [@3] In what direction does the 5-year risk change when you change any
   of the predictor variables keeping the other predictor variables at
   a fixed value?

- Age: Risk increases 
- Sex: Men have higher risk
- Diabetes duration: Risk increases
- Systolic blood pressure: Risk increases
- Albuminuria: Risk increases
- LDL: Risk increases
- eGFR: Risk increases
- Current smoker: Risk higher
- Regular excercise: Risk lower

4. [@4] What other risk predictor variables does the Framingham 
   CVD risk calculator use? https://static.heart.org/riskcalc/app/index.html

Total cholesterol, HDL cholesterol, Treatment with Statin, Treatment for Hypertension, Aspirin Therapy


\noindent Think about and discuss the following with your nearest neighbors:

5. [@5] What possible applications does this medical risk prediction model have?

- Inform patients
- Guide patients  
- Select patients for RCTs
- Related research projects

6. [@6] Which of the risk factors may change over time?

HbA1c, LDL, Albuminuria, eGFR, Systolic blood pressure, Regular excercise, Current smoker, Diabetes duration, Age

7. [@7] How old (relative to time zero) are the measurements of these risk factors allowed to be?

This is not stated. Intuitively it seems that the measurements need to be recent.

8. [@8] Which of the risk factors are modifiable?

Systolic blood pressure, albuminuria, eGFR, LDL, smoking, regular
exercise

9. [@9] Correspondingly what would be possible interventions?

Stop smoking, start regular exercised, treatment for hypertension,
blood sugar control, dietary modification, statins, renal replacement
therapy, dialysis.

10. [@10] Decision making (for versus against an intervention) could be based
   on comparing the predicted 5-year risk to a fixed threshold, e.g.,
   10%. How would one incorporate lower and upper limits for the
   predicted risks to guide a person's decision?

A conservative strategy would only recommend treatment when the upper
limit of the predicted risk is above the threshold, an agressive
strategy would recommend treatment when the lower limit exceeds the
threshold.

